version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DEFAULT_USER: postgres
            ADMINER_DEFAULT_PASSWORD: password
